### ISSUE TITLE
animation effects

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/css-text-portrait-builder#19]
An option to add animation effects to the text and image. 🤯
Amazing right? 😎 I will work on it once I fully polished the building process.

- [ ] Animation for Text
- [ ] Animation for Image

**Comment by WarenGonzaga** [comment]
I'm considering adding this to the next version after v1.2.0.

**Comment by ravzkie12** [comment]
Hello sir, are you gonna use some library or just plain js?

**Comment by WarenGonzaga** [comment]
> Hello sir, are you gonna use some library or just plain js?

CSS would work, I guess.

**Comment by warengonzaga** [comment]
I'll probably abandon this as I don't see a reason why we need an animation for portrait. Maybe if someone able to share some ideas I'll make it happen.
