### ISSUE TITLE
official documentation

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/css-text-portrait-builder#2]
I'm currently working on documentation so please be patient at the moment.
You can check the readme steps for now. If you need further help please use our [Q&A section](https://github.com/WarenGonzaga/css-text-portrait-builder/discussions/new?category=q-a). 🙏😇

**Comment by WarenGonzaga** [comment]
Must have docs for the following:

- [ ] Building on Desktop
- [ ] Building on Mobile

**Comment by WarenGonzaga** [comment]
Documentation is now live, but still in progress. It will update from time to time. ☕
Please be patient as I'm working in my free time. 😅

**Comment by remuz-br** [comment]
$ rimraf dist
'rimraf' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by WarenGonzaga** [comment]
> 

Please check the [FAQ](https://github.com/WarenGonzaga/css-text-portrait-builder/discussions?discussions_q=label%3Afaq) section first.

**Comment by WarenGonzaga** [comment]
The basic documentation is now complete. I will add information from time to time. Closing this issue now.
