### ISSUE TITLE
migrate to modern yarn

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/css-text-portrait-builder#22]
The migration process is perfectly documented here: https://yarnpkg.com/getting-started/migration

**Comment by jaacqueees** [comment]
![image](https://user-images.githubusercontent.com/73355252/142749892-bdbd729f-7c27-4b8a-8b11-115d12877d92.png)

**Comment by WarenGonzaga** [comment]
migrated to yarn v2 with no problems. 😎
