### ISSUE TITLE
shareable links

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/css-text-portrait-builder#34]
A user suggested it to me to add a way to share their builds with a shareable link.
For me, it's a brilliant idea, and considering adding this to my roadmap. 🥰

**Comment by WarenGonzaga** [comment]
The instant build currently can offer shareable links. This feature is for manual builders. Meaning this feature is not a priority. I can consider this in the future for now instant builds via Gitpod would work for sharing your builds as a link.

**Comment by WarenGonzaga** [comment]
For the shareable links, I guess we can use file.io API to temporarily upload and download the exported builds and shareable using links. Basically, a ready-to-use builds that can be downloaded somewhere.

Previewable links I guess I'll create a separate task for it.

**Comment by WarenGonzaga** [comment]
Shareable Link Features:

- [ ] Shareable Exports
- [ ] Shareable Previews

Good to create a separate issue for this...

**Comment by warengonzaga** [comment]
Not possible directly within the builder, will add documentation on how to upload your builds to netlify for more customization support.
