### ISSUE TITLE
dynamically update max chars

### ISSUE THREAD

**Issue by decanTyme** [WarenGonzaga/css-text-portrait-builder#50]
**Is your feature request related to a problem? Please describe.**
Max characters needed to fill the screen had to be calculated through trial and error. This also had to be recalculated when changing font families or sizes, for example. On orientation/page zoom/window resize, recalculate. More on https://github.com/WarenGonzaga/css-text-portrait-builder/pull/43#issuecomment-980790904.

**Describe the solution you'd like**
There should be a function to dynamically calculate `maxChar` based on at least these contexts: `font-family`, `font-size`, and screen dimensions/magnification. Something like this:

![2021-11-28 22-45-00_Trim](https://user-images.githubusercontent.com/74456102/143780511-22b93d17-927e-4214-8759-a5a5dab18f40.gif)

![2021-11-29-02-50-08](https://user-images.githubusercontent.com/74456102/143781794-c9922fcf-652f-4f9d-9bcc-c1559bdda4a6.gif)

I worked some initial code and set it to _50%_ fill to better see it dynamically update. While it does not perfectly fill at 50%, <ins>at 100% it should eliminate any whitespaces and effectively fill the screen</ins>.

Might PR this if everyone also agrees or wants this feature.

**Comment by WarenGonzaga** [comment]
Great work @decanTyme! Send a suggested PR for that. Good catch btw. 👌

**Comment by WarenGonzaga** [comment]
I guess we can safely close this? @decanTyme as it is already in the pending release PR.

**Comment by decanTyme** [comment]
> I guess we can safely close this? @decanTyme as it is already in the pending release PR.

Oh right, I can close this now. Thanks for reminding!
